[project]
name = "ravenfall-channelbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles==24.1.0",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.13.2",
    "aiosignal==1.4.0",
    "aiosqlite==0.21.0",
    "anyio==4.9.0",
    "async-lru==2.0.5",
    "attrs==25.4.0",
    "bidict>=0.23.1",
    "certifi==2025.4.26",
    "colorama==0.4.6",
    "docstring-parser>=0.17.0",
    "enum-tools==0.13.0",
    "frozenlist==1.8.0",
    "greenlet==3.2.3",
    "h11==0.16.0",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "idna==3.11",
    "msgspec>=0.20.0",
    "multidict==6.7.0",
    "numerize>=0.12",
    "propcache==0.4.1",
    "psutil==7.0.0",
    "pydantic>=2.12.5",
    "pygments==2.19.2",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.1.0",
    "rapidfuzz==3.13.0",
    "ruamel-yaml==0.18.14",
    "ruamel-yaml-clib==0.2.12",
    "six==1.17.0",
    "sniffio==1.3.1",
    "sqlalchemy==2.0.41",
    "thefuzz==0.22.1",
    "tinydb==4.8.2",
    "tqdm==4.67.1",
    "twitchapi",
    "typing-extensions==4.15.0",
    "websockets==15.0.1",
    "yarl==1.22.0",
]

[tool.basedpyright]
reportImportCycles = "information"
reportImplicitStringConcatenation = "none"
reportPrivateUsage = "none"

[tool.ty.rules]
all = "error"

[tool.pyrefly]

[tool.pyrefly.errors]
implicit-any = "warn"
implicitly-defined-attribute = "warn"
unannotated-attribute = "warn"
unannotated-parameter = "warn"
untyped-import = "warn"
missing-source = "warn"
unused-ignore = "warn"
missing-override-decorator = "warn"
not-required-key-access = "warn"
open-unpacking = "warn"

[tool.ruff]
line-length = 90

[tool.ruff.lint]
future-annotations = true
select = ['ALL']
ignore = [
    "F821",
    "G004",
    "D100",
    "D104",
    "D105",
    "D107",
    "ASYNC109",
    "B010",
    "B009",
    "ERA",
    "INP",
    "COM",
    "ANN",
    "TRY301",
    "FBT003",
    "SIM108",
    "TRY400",
    "PLR0913",
    "C901",
    "PLR0912",
    "PLR0915",
    "SLF001",
]

[tool.ruff.format]
exclude = ["./twitchAPI/**"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.uv.sources]
twitchapi = { git = "https://github.com/abrokecube/pyTwitchAPI", rev = "master" }
