"""
This type stub file was generated by pyright.
"""

translation_table = ...
def ascii_only(s):
    ...

def full_process(s, force_ascii=...) -> str:
    """
    Process string by
    -- removing all but letters and numbers
    -- trim whitespace
    -- force to lower case
    if force_ascii == True, force convert to ascii
    """
    ...

